version: 0.2
env:
  secrets-manager:
    PROXY_URL: "vaylariski_app_dev:proxy_url"
    REACT_APP_BASE_REST_URL: "vaylariski_app_dev:REACT_APP_BASE_REST_URL"
phases:
  pre_build:
    commands:
      - echo Logging to ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_BASEIMAGE_REPOSITORY_URI
      - set
  build:
    commands:
      - echo Build started on `date`
      - docker build -f Dockerfile.aws
        --build-arg PROXY_URL=${PROXY_URL}
        --build-arg REACT_APP_BASE_REST_URL=${REACT_APP_BASE_REST_URL}
        -t $ECR_REPOSITORY_NAME:latest .
  post_build:
    commands:
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_BUILDIMAGE_REPOSITORY_URI
      - echo Post-build started on `date`
      - docker tag $ECR_REPOSITORY_NAME:latest $ECR_BUILDIMAGE_REPOSITORY_URI:latest
      - docker tag $ECR_BUILDIMAGE_REPOSITORY_URI:latest $ECR_BUILDIMAGE_REPOSITORY_URI:$CODEBUILD_BUILD_NUMBER
      - docker push $ECR_BUILDIMAGE_REPOSITORY_URI:latest
      - docker push $ECR_BUILDIMAGE_REPOSITORY_URI:$CODEBUILD_BUILD_NUMBER
      - printf '[{"name":"%s","imageUri":"%s"}]' $ECS_SERVICE_NAME $ECR_BUILDIMAGE_REPOSITORY_URI:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
