version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging to ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_BASEIMAGE_REPOSITORY_URI
      - set
      - echo Installing npm dependencies...
      - npm install
      - npm install react-scripts --silent
  build:
    commands:
      - echo Build started on `date`
      - npm run build
      - docker build -f Dockerfile.aws -t $ECR_REPOSITORY_NAME:latest .
  post_build:
    commands:
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_BUILDIMAGE_REPOSITORY_URI
      - echo Post-build started on `date`
      - docker tag $ECR_REPOSITORY_NAME:latest $ECR_BUILDIMAGE_REPOSITORY_URI:latest
      - docker tag $ECR_BUILDIMAGE_REPOSITORY_URI:latest $ECR_BUILDIMAGE_REPOSITORY_URI:$CODEBUILD_BUILD_NUMBER
      - docker push $ECR_BUILDIMAGE_REPOSITORY_URI:latest
      - docker push $ECR_BUILDIMAGE_REPOSITORY_URI:$CODEBUILD_BUILD_NUMBER
      - printf '[{"name":"%s","imageUri":"%s"}]' $ECS_SERVICE_NAME $ECR_BUILDIMAGE_REPOSITORY_URI:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
