FROM 894932018761.dkr.ecr.eu-west-1.amazonaws.com/node:12-alpine

RUN mkdir -p /usr/app/
WORKDIR /usr/src/app/

COPY package*.json ./

RUN npm install

# Bundle app source
COPY . .

EXPOSE 3000
CMD [ "npm", "start" ]