FROM 894932018761.dkr.ecr.eu-west-1.amazonaws.com/node:16.18.1-alpine

ARG PROXY_URL

WORKDIR /app

COPY . .
ENV GENERATE_SOURCEMAP=false
ENV PROXY_URL=${PROXY_URL}
ENV WDS_SOCKET_PORT=0

#install packages
RUN npm i
#build the app
# RUN npm run build


EXPOSE 3000
# CMD ["npx", "serve","-l", "3000", "-s", "build" ]
CMD ["npm", "start"]