FROM 894932018761.dkr.ecr.eu-west-1.amazonaws.com/node:16.18.1-alpine

ARG REACT_APP_BASE_REST_URL
ENV REACT_APP_BASE_REST_URL="/"

WORKDIR /app

COPY . .
ENV GENERATE_SOURCEMAP=false
ENV REACT_APP_BASE_REST_URL="http://vaylariski:8080/"
#install packages
RUN npm ci
#build the app
RUN npm run build


EXPOSE 3000
CMD ["npx", "serve", "-s", "build" ]