export const resultRowsEnums = {
  POINT_INDEX: "point_index",
  GDO_GID: "GDO_GID",
  VAYLAT: "VAYLAT",
  RISK_INDEX_SUM: "RISK_INDEX_SUM",
  RIV_1_CHANNEL: "RIV_1_channel",
  RIV_2_BEND: "RIV_2_bend",
  RIV_3_S_BEND: "RIV_3_s_bend",
  RIV_4_TRAFFIC_COMPLEXITY: "RIV_4_traffic_complexity",
  RIV_5_REDUCED_VISIBILITY: "RIV_5_reduced_visibility",
  RIV_6_LIGHT_POLLUTION: "RIV_6_light_pollution",
  PF_1_CHANNEL: "PF_1_channel",
  PF_2_BEND: "PF_2_bend",
  PF_BEND_1: "PF_bend1",
  PF_BEND_2: "PF_bend2",
  BSI: "BSI",
  PF_3_S_BEND: "PF_3_s_bend",
  PF_4_TRAFFIC_COMPLEXITY: "PF_4_traffic_complexity",
  PF_5_REDUCED_VISIBILITY: "PF_5_reduced_visibility",
  PF_6_LIGHT_POLLUTION: "PF_6_light_pollution",
  PF_6_LIGHT_POLLUTION_VALUE: "PF_6_light_pollution_value",
  PF_TRAFFIC_COMPLEXITY: "PF_traffic_complexity",
  PF_TRAFFIC_VALUE: "PF_traffic_value",
  PF_TRAFFIC_VOLUME: "PF_traffic_volume",
  W_ATN: "W_atn",
  W_BANK_CLEARANCE: "W_bank_clearance",
  W_BOTTOM_SURFACE: "W_bottom_surface",
  W_CHANNEL: "W_channel",
  W_CHANNEL_DEPTH: "W_channel_depth",
  W_CROSS_CURRENT: "W_cross_current",
  W_LONGITUDINAL_CURRENT: "W_longitudinal_current",
  W_MANOEUVRABILITY: "W_manoeuvrability",
  W_SPEED: "W_speed",
  W_WAVE_HEIGHT: "W_wave_height",
  W_WIND: "W_wind",
  AIDS_TO_NAVIGATION_CATEGORY: "aids_to_navigation_category",
  BEND_S_LENGTH: "bend_S_length",
  BEND_ANGLE: "bend_angle",
  BEND_RADIUS: "bend_radius",
  BOTTOM_SURFACE_CATEGORY: "bottom_surface_category",
  CHANNEL_DEPTH_VALUE: "channel_depth_value",
  CHANNEL_EDGE_TYPE: "channel_edge_type",
  CHANNEL_TYPE: "channel_type",
  CROSS_CURRENT_CATEGORY: "cross_current_category",
  LONGITUDINAL_CURRENT_CATEGORY: "longitudinal_current_category",
  NUMBER_OF_LANES: "number_of_lanes",
  VESSEL_SPEED_CATEGORY: "vessel_speed_category",
  VISIBILITY: "visibility",
  WAVE_HEIGHT_CATEGORY: "wave_height_category",
  WIND_SPEED_CATEGORY: "wind_speed_category",
  MID_POINT: "MID_POINT",
};

export const cssColorCodes = {
  // BACKGROUND_WHITE: ""#",fffff",
  // HEADER: ""#",3d0fc",
  // SUBMIT_BUTTON: ""#",ebebe",
  // TAB: ""#",4e1f8",
  // TAB_TEXT: ""#",65656",
  // CONTAINER: ""#",9edfb",
  // TABLE_CONTAINER: ""#",9edfb",
  // GREEN: ""#",07a43",
  // YELLOW: ""#",fc300",
  // RED: ""#",73f00",
  // BLACK: ""#",00000",

  WHITE: "#ffffff",

  BLACK_100: "#000000",
  BLACK_70: "#58595b",
  BLACK_50: "#939598",
  BLACK_30: "#d1d3d4",

  DARK_BLUE_100: "#0064af",
  DARK_BLUE_70: "#4d93c7",
  DARK_BLUE_50: "#80b2d7",
  DARK_BLUE_30: "#b3d1e7",

  BLUE_100: "#0099ff",
  BLUE_70: "#4db9ea",
  BLUE_50: "#80cdf0",
  BLUE_30: "#b3e1f6",

  LIGHT_BLUE_100: "#49c2f1",
  LIGHT_BLUE_70: "#80d4f5",
  LIGHT_BLUE_50: "#a4e1f8",
  LIGHT_BLUE_30: "#c9edfb",

  TURQUOISE_100: "#00b0cc",
  TURQUOISE_70: "#4dc8db",
  TURQUOISE_50: "#80d7e6",
  TURQUOISE_30: "#b3e7f0",

  GREEN_100: "#207a43",
  GREEN_70: "#63a27b",
  GREEN_50: "#8fbca1",
  GREEN_30: "#bcd7c6",

  LIGHT_GREEN_100: "#8dcb6d",
  LIGHT_GREEN_70: "#afdb99",
  LIGHT_GREEN_50: "#c6e5b6",
  LIGHT_GREEN_30: "#ddefd3",

  YELLOW_100: "#ffc300",
  YELLOW_70: "#ffd54d",
  YELLOW_50: "#ffe180",
  YELLOW_30: "#ffedb3",

  PURPLE_100: "#910aa3",
  PURPLE_70: "#ab5dba",
  PURPLE_50: "#c38bce",
  PURPLE_30: "#dbbae1",

  RED_100: "#c73f00",
  RED_70: "#d7784d",
  RED_50: "#e39f80",
  RED_30: "#eec5b3",

  ORANGE_100: "#ff5100",
  ORANGE_70: "#ff854d",
  ORANGE_50: "#ffa880",
  ORANGE_30: "#ffcbb3",

  MAGENTA_100: "#e50083",
  MAGENTA_70: "#e7389e",
  MAGENTA_50: "#f083c2",
  MAGENTA_30: "#f9cee7",

  BACKGROUND_WHITE: "#ffffff", // Same as WHITE
  HEADER: "#63d0fc",
  TAB: "#a4e1f8", // Same as LIGHT_BLUE_50
  TAB_TEXT: "#58595b", // Same as BLACK_70
  CONTAINER: "#c9edfb", // Same as LIGHT_BLUE_30
};
