import { resultRowsEnums } from "./enums";

export const TableViewColumns = [
  {
    key: resultRowsEnums.POINT_INDEX,
    name: "indeksi",
    resizable: true,
    sortable: true,
  },
  {
    key: resultRowsEnums.GDO_GID,
    name: "GDO_GID",
    resizable: true,
    sortable: true,
  },
  {
    key: resultRowsEnums.VAYLAT,
    name: "VAYLAT",
    resizable: true,
    sortable: true,
  },
  {
    key: resultRowsEnums.RISK_INDEX_SUM,
    name: "RIV summa",
    resizable: true,
    sortable: true,
  },
  {
    key: resultRowsEnums.RIV_1_CHANNEL,
    name: "RIV väylä",
    resizable: true,
    sortable: true,
  },
  {
    key: resultRowsEnums.RIV_2_BEND,
    name: "RIV mutka",
    resizable: true,
    sortable: true,
  },
  {
    key: resultRowsEnums.RIV_3_S_BEND,
    name: "RIV S-mutka",
    resizable: true,
    sortable: true,
  },
  {
    key: resultRowsEnums.RIV_4_TRAFFIC_COMPLEXITY,
    name: "RIV liikenne",
    resizable: true,
    sortable: true,
  },
  {
    key: resultRowsEnums.RIV_5_REDUCED_VISIBILITY,
    name: "RIV heikentynyt näkyvyys",
    resizable: true,
    sortable: true,
  },
  {
    key: resultRowsEnums.RIV_6_LIGHT_POLLUTION,
    name: "RIV taustavalon voimakkuus",
    resizable: true,
    sortable: true,
  },
  {
    key: resultRowsEnums.PF_1_CHANNEL,
    name: "väylän vaikuttavuus",
    resizable: true,
    sortable: true,
  },
  {
    key: resultRowsEnums.PF_2_BEND,
    name: "mutkan vaikuttavuus",
    resizable: true,
    sortable: true,
  },
  {
    key: resultRowsEnums.PF_3_S_BEND,
    name: "S-mutkan vaikuttavuus",
    resizable: true,
    sortable: true,
  },
  {
    key: resultRowsEnums.PF_4_TRAFFIC_COMPLEXITY,
    name: "liikenteen vaikuttavuus",
    resizable: true,
    sortable: true,
  },
  {
    key: resultRowsEnums.PF_5_REDUCED_VISIBILITY,
    name: "heikentyneen näkyvyyden vaikuttavuus",
    resizable: true,
    sortable: true,
  },
  {
    key: resultRowsEnums.PF_6_LIGHT_POLLUTION_VALUE,
    name: "taustavalon vaikuttavuus",
    resizable: true,
    sortable: true,
  },
  {
    key: resultRowsEnums.W_CHANNEL,
    name: "väylän leveys [m]",
    resizable: true,
    sortable: true,
  },
  {
    key: resultRowsEnums.CHANNEL_DEPTH_VALUE,
    name: "väylän syvyys [m]",
    resizable: true,
    sortable: true,
  },
  {
    key: resultRowsEnums.BEND_S_LENGTH,
    name: "S-mutka [m]",
    resizable: true,
    sortable: true,
  },
  {
    key: resultRowsEnums.BEND_ANGLE,
    name: "mutkan suuntakulma [°]",
    resizable: true,
    sortable: true,
  },
  {
    key: resultRowsEnums.BEND_RADIUS,
    name: "mutkan säde [m]",
    resizable: true,
    sortable: true,
  },
  {
    key: resultRowsEnums.PF_BEND_1,
    name: "PF_bend1",
    resizable: true,
    sortable: true,
  },
  {
    key: resultRowsEnums.PF_BEND_2,
    name: "PF_bend2",
    resizable: true,
    sortable: true,
  },
  {
    key: resultRowsEnums.BSI,
    name: "BSI",
    resizable: true,
    sortable: true,
  },
  {
    key: resultRowsEnums.MID_POINT,
    name: "koordinaatit",
    resizable: true,
    sortable: true,
  },
  {
    key: resultRowsEnums.W_ATN,
    name: "ATN painokerroin",
    resizable: true,
    sortable: true,
  },
  {
    key: resultRowsEnums.W_BANK_CLEARANCE,
    name: "reunan painokerroin",
    resizable: true,
    sortable: true,
  },
  {
    key: resultRowsEnums.W_BOTTOM_SURFACE,
    name: "pohjan painokerroin",
    resizable: true,
    sortable: true,
  },
  {
    key: resultRowsEnums.W_CHANNEL_DEPTH,
    name: "syvyyden painokerroin",
    resizable: true,
    sortable: true,
  },
  {
    key: resultRowsEnums.W_CROSS_CURRENT,
    name: "poikkivirtauksen painokerroin",
    resizable: true,
    sortable: true,
  },
  {
    key: resultRowsEnums.W_LONGITUDINAL_CURRENT,
    name: "pitkittäisvirtauksen painokerroin",
    resizable: true,
    sortable: true,
  },
  {
    key: resultRowsEnums.W_MANOEUVRABILITY,
    name: "ohjailtavuuden painokerroin",
    resizable: true,
    sortable: true,
  },
  {
    key: resultRowsEnums.W_SPEED,
    name: "nopeuden painokerroin",
    resizable: true,
    sortable: true,
  },
  {
    key: resultRowsEnums.W_WAVE_HEIGHT,
    name: "aallon painokerroin",
    resizable: true,
    sortable: true,
  },
  {
    key: resultRowsEnums.W_WIND,
    name: "tuulen painokerroin",
    resizable: true,
    sortable: true,
  },
  {
    key: resultRowsEnums.AIDS_TO_NAVIGATION_CATEGORY,
    name: "ATN",
    resizable: true,
    sortable: true,
  },
  {
    key: resultRowsEnums.PF_6_LIGHT_POLLUTION,
    name: "taustavalon voimakkuus",
    resizable: true,
    sortable: true,
  },

  {
    key: resultRowsEnums.PF_TRAFFIC_COMPLEXITY,
    name: "liikenteen monimutkaisuus",
    resizable: true,
    sortable: true,
  },
  {
    key: resultRowsEnums.PF_TRAFFIC_VALUE,
    name: "liikenteen monimutkaisuuskerroin",
    resizable: true,
    sortable: true,
  },
  {
    key: resultRowsEnums.PF_TRAFFIC_VOLUME,
    name: "liikenteen määrä",
    resizable: true,
    sortable: true,
  },
  {
    key: resultRowsEnums.BOTTOM_SURFACE_CATEGORY,
    name: "pohja",
    resizable: true,
    sortable: true,
  },
  {
    key: resultRowsEnums.CHANNEL_EDGE_TYPE,
    name: "reunan tyyppi",
    resizable: true,
    sortable: true,
  },
  {
    key: resultRowsEnums.CHANNEL_TYPE,
    name: "väylän tyyppi",
    resizable: true,
    sortable: true,
  },
  {
    key: resultRowsEnums.CROSS_CURRENT_CATEGORY,
    name: "poikkivirtaus",
    resizable: true,
    sortable: true,
  },
  {
    key: resultRowsEnums.LONGITUDINAL_CURRENT_CATEGORY,
    name: "pitkittäisvirtaus",
    resizable: true,
    sortable: true,
  },
  {
    key: resultRowsEnums.NUMBER_OF_LANES,
    name: "kaistat",
    resizable: true,
    sortable: true,
  },
  {
    key: resultRowsEnums.VESSEL_SPEED_CATEGORY,
    name: "aluksen nopeusluokka",
    resizable: true,
    sortable: true,
  },
  {
    key: resultRowsEnums.VISIBILITY,
    name: "näkyvyys [m]",
    resizable: true,
    sortable: true,
  },
  {
    key: resultRowsEnums.WAVE_HEIGHT_CATEGORY,
    name: "aallon korkeus",
    resizable: true,
    sortable: true,
  },
  {
    key: resultRowsEnums.WIND_SPEED_CATEGORY,
    name: "tuulen nopeusluokka",
    resizable: true,
    sortable: true,
  },
];
