import { resultRowsEnums } from "./enums";

export const TableViewColumns = [
  {
    // key: "point_index",
    key: resultRowsEnums.POINT_INDEX,
    name: "index",
    resizable: true,
    sortable: true,
  },
  {
    // key: "GDO_GID",
    key: resultRowsEnums.GDO_GID,
    name: "GDO_GID",
    resizable: true,
    sortable: true,
  },
  {
    // key: "VAYLAT",
    key: resultRowsEnums.VAYLAT,
    name: "VAYLAT",
    resizable: true,
    sortable: true,
  },
  {
    // key: "RISK_INDEX_SUM",
    key: resultRowsEnums.RISK_INDEX_SUM,
    name: "RIV_SUM",
    resizable: true,
    sortable: true,
  },
  {
    // key: "RIV_1_channel",
    key: resultRowsEnums.RIV_1_CHANNEL,
    name: "RIV_1_channel",
    resizable: true,
    sortable: true,
  },
  {
    // key: "RIV_2_bend",
    key: resultRowsEnums.RIV_2_BEND,
    name: "RIV_2_bend",
    resizable: true,
    sortable: true,
  },
  {
    // key: "RIV_3_s_bend",
    key: resultRowsEnums.RIV_3_S_BEND,
    name: "RIV_3_s_bend",
    resizable: true,
    sortable: true,
  },
  {
    // key: "RIV_4_traffic_complexity",
    key: resultRowsEnums.RIV_4_TRAFFIC_COMPLEXITY,
    name: "RIV_4_traffic_complexity",
    resizable: true,
    sortable: true,
  },
  {
    // key: "RIV_5_reduced_visibility",
    key: resultRowsEnums.RIV_5_REDUCED_VISIBILITY,
    name: "RIV_5_reduced_visibility",
    resizable: true,
    sortable: true,
  },
  {
    // key: "RIV_6_light_pollution",
    key: resultRowsEnums.RIV_6_LIGHT_POLLUTION,
    name: "RIV_6_light_pollution",
    resizable: true,
    sortable: true,
  },
  {
    // key: "PF_1_channel",
    key: resultRowsEnums.PF_1_CHANNEL,
    name: "PF_1_channel",
    resizable: true,
    sortable: true,
  },
  {
    // key: "PF_2_bend",
    key: resultRowsEnums.PF_2_BEND,
    name: "PF_2_bend",
    resizable: true,
    sortable: true,
  },
  {
    // key: "PF_bend1",
    key: resultRowsEnums.PF_BEND_1,
    name: "PF_bend1",
    resizable: true,
    sortable: true,
  },
  {
    // key: "PF_bend2",
    key: resultRowsEnums.PF_BEND_2,
    name: "PF_bend2",
    resizable: true,
    sortable: true,
  },
  {
    // key: "BSI",
    key: resultRowsEnums.BSI,
    name: "BSI",
    resizable: true,
    sortable: true,
  },
  {
    // key: "PF_3_s_bend",
    key: resultRowsEnums.PF_3_S_BEND,
    name: "PF_3_s_bend",
    resizable: true,
    sortable: true,
  },
  {
    // key: "PF_4_traffic_complexity",
    key: resultRowsEnums.PF_4_TRAFFIC_COMPLEXITY,
    name: "PF_4_traffic_complexity",
    resizable: true,
    sortable: true,
  },
  {
    // key: "PF_5_reduced_visibility",
    key: resultRowsEnums.PF_5_REDUCED_VISIBILITY,
    name: "PF_5_reduced_visibility",
    resizable: true,
    sortable: true,
  },
  {
    // key: "PF_6_light_pollution",
    key: resultRowsEnums.PF_6_LIGHT_POLLUTION,
    name: "PF_6_light_pollution",
    resizable: true,
    sortable: true,
  },
  {
    // key: "PF_6_light_pollution_value",
    key: resultRowsEnums.PF_6_LIGHT_POLLUTION_VALUE,
    name: "PF_6_light_pollution_value",
    resizable: true,
    sortable: true,
  },
  {
    // key: "PF_traffic_complexity",
    key: resultRowsEnums.PF_TRAFFIC_COMPLEXITY,
    name: "PF_traffic_complexity",
    resizable: true,
    sortable: true,
  },
  {
    // key: "PF_traffic_value",
    key: resultRowsEnums.PF_TRAFFIC_VALUE,
    name: "PF_traffic_value",
    resizable: true,
    sortable: true,
  },
  {
    // key: "PF_traffic_volume",
    key: resultRowsEnums.PF_TRAFFIC_VOLUME,
    name: "PF_traffic_volume",
    resizable: true,
    sortable: true,
  },
  {
    // key: "W_atn",
    key: resultRowsEnums.W_ATN,
    name: "W_atn",
    resizable: true,
    sortable: true,
  },
  {
    // key: "W_bank_clearance",
    key: resultRowsEnums.W_BANK_CLEARANCE,
    name: "W_bank_clearance",
    resizable: true,
    sortable: true,
  },
  {
    // key: "W_bottom_surface",
    key: resultRowsEnums.W_BOTTOM_SURFACE,
    name: "W_bottom_surface",
    resizable: true,
    sortable: true,
  },
  {
    // key: "W_channel",
    key: resultRowsEnums.W_CHANNEL,
    name: "W_channel_width",
    resizable: true,
    sortable: true,
  },
  {
    // key: "W_channel_depth",
    key: resultRowsEnums.W_CHANNEL_DEPTH,
    name: "W_channel_depth",
    resizable: true,
    sortable: true,
  },
  {
    // key: "W_cross_current",
    key: resultRowsEnums.W_CROSS_CURRENT,
    name: "W_cross_current",
    resizable: true,
    sortable: true,
  },
  {
    // key: "W_longitudinal_current",
    key: resultRowsEnums.W_LONGITUDINAL_CURRENT,
    name: "W_longitudinal_current",
    resizable: true,
    sortable: true,
  },
  {
    // key: "W_manoeuvrability",
    key: resultRowsEnums.W_MANOEUVRABILITY,
    name: "W_manoeuvrability",
    resizable: true,
    sortable: true,
  },
  {
    // key: "W_speed",
    key: resultRowsEnums.W_SPEED,
    name: "W_speed",
    resizable: true,
    sortable: true,
  },
  {
    // key: "W_wave_height",
    key: resultRowsEnums.W_WAVE_HEIGHT,
    name: "W_wave_height",
    resizable: true,
    sortable: true,
  },
  {
    // key: "W_wind",
    key: resultRowsEnums.W_WIND,
    name: "W_wind",
    resizable: true,
    sortable: true,
  },
  {
    // key: "aids_to_navigation_category",
    key: resultRowsEnums.AIDS_TO_NAVIGATION_CATEGORY,
    name: "ATN",
    resizable: true,
    sortable: true,
  },
  {
    // key: "bend_S_length",
    key: resultRowsEnums.BEND_S_LENGTH,
    name: "S_bend_length",
    resizable: true,
    sortable: true,
  },
  {
    // key: "bend_angle",
    key: resultRowsEnums.BEND_ANGLE,
    name: "bend_angle",
    resizable: true,
    sortable: true,
  },
  {
    // key: "bend_radius",
    key: resultRowsEnums.BEND_RADIUS,
    name: "bend_radius",
    resizable: true,
    sortable: true,
  },
  {
    // key: "bottom_surface_category",
    key: resultRowsEnums.BOTTOM_SURFACE_CATEGORY,
    name: "bottom_surface_category",
    resizable: true,
    sortable: true,
  },
  {
    // key: "channel_depth_value",
    key: resultRowsEnums.CHANNEL_DEPTH_VALUE,
    name: "channel_depth_value",
    resizable: true,
    sortable: true,
  },
  {
    // key: "channel_edge_type",
    key: resultRowsEnums.CHANNEL_EDGE_TYPE,
    name: "channel_edge_type",
    resizable: true,
    sortable: true,
  },
  {
    // key: "channel_type",
    key: resultRowsEnums.CHANNEL_TYPE,
    name: "channel_type",
    resizable: true,
    sortable: true,
  },
  {
    // key: "cross_current_category",
    key: resultRowsEnums.CROSS_CURRENT_CATEGORY,
    name: "cross_current_category",
    resizable: true,
    sortable: true,
  },
  {
    // key: "longitudinal_current_category",
    key: resultRowsEnums.LONGITUDINAL_CURRENT_CATEGORY,
    name: "longitudinal_current_category",
    resizable: true,
    sortable: true,
  },
  {
    // key: "number_of_lanes",
    key: resultRowsEnums.NUMBER_OF_LANES,
    name: "number_of_lanes",
    resizable: true,
    sortable: true,
  },
  {
    // key: "vessel_speed_category",
    key: resultRowsEnums.VESSEL_SPEED_CATEGORY,
    name: "vessel_speed_category",
    resizable: true,
    sortable: true,
  },
  {
    // key: "visibility",
    key: resultRowsEnums.VISIBILITY,
    name: "visibility",
    resizable: true,
    sortable: true,
  },
  {
    // key: "wave_height_category",
    key: resultRowsEnums.WAVE_HEIGHT_CATEGORY,
    name: "wave_height_category",
    resizable: true,
    sortable: true,
  },
  {
    // key: "wind_speed_category",
    key: resultRowsEnums.WIND_SPEED_CATEGORY,
    name: "wind_speed_category",
    resizable: true,
    sortable: true,
  },
  {
    // key: "MID_POINT",
    key: resultRowsEnums.MID_POINT,
    name: "point_coordinate",
    resizable: true,
    sortable: true,
  },
];
