name: CI-pipeline for running E2E tests

on:
  push:
    branches:
      - dev
      - test
      - prod
  pull_request:
    branches:
      - dev
      - test
      - prod

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    # container: cypress/browsers:node-16.18.1-chrome-110.0.5481.96-1-ff-109.0-edge-110.0.1587.41-1
    steps:
      - name: Setup Node 24.0
        uses: actions/setup-node@v4
        with:
          node-version: 24.0

      - name: Checkout backend
        uses: actions/checkout@v4
        with:
          repository: finnishtransportagency/vaylariski
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          ref: ${{ github.base_ref || github.ref_name }}
          # base_ref = target branch (pull requests)
          # ref_name = branch that triggered the workflow (push)

      - name: Run backend with docker compose and conduct a healthcheck
        run: |
          docker compose -f "docker-compose.e2e.yaml" -p vaylariski-frontend up --build -d
          docker rename vaylariski-frontend-postgres-1 vaylariski-frontend_postgres_1
          timeout 60s sh -c 'until docker ps | grep backend | grep -q healthy; do echo "Waiting for backend container to be healthy..."; sleep 2; done'

      - name: Checkout frontend
        uses: actions/checkout@v4

      - name: Build frontend with docker
        run: |
          DOCKER_BUILDKIT=0 docker build -t vaylariski-frontend --build-arg PROXY_URL=http://vaylariski_backend_e2e_test:8080 --build-arg REACT_APP_BASE_REST_URL=vaylariski/rest .

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build:
          record: false
          start: docker run -p 3000:3000 --network=vaylariski-frontend_default vaylariski-frontend:latest
          wait-on: 'http://localhost:3000'
          browser: chrome
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Upload failure screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
